version: '3'

services:
  db:
    image: mysql:5
    environment:
      - "MYSQL_ROOT_PASSWORD=mysql_passwd"
    volumes:
      - mysql:/var/lib/mysql
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    links:
      - "db"
volumes:
  mysql:
